[env:nodemcu-32s]
platform = espressif32
board = nodemcu-32s
framework = arduino
monitor_speed = 115200
upload_speed = 921600

board_build.filesystem = littlefs

lib_deps = 
  bodmer/TFT_eSPI@^2.5.43
  https://github.com/PaulStoffregen/XPT2046_Touchscreen.git#v1.4
  lvgl/lvgl@^8.3.11

build_flags =
  -D USER_SETUP_LOADED=1
  -include src/Setup_ESP32_2432S028R_ST7789.h
  -D LV_CONF_INCLUDE_SIMPLE
  -include src/lv_conf.h
